"""PDF translation pipeline — re-exports from the _core module.

The original pdf_translation.py (~3300 lines) has been moved here as _core.py.
This wrapper provides clean imports while allowing gradual decomposition.
"""

from ._core import (  # noqa: F401
    PDF_TYPE_NATIVE,
    PDF_TYPE_SCANNED,
    PDF_PROCESSING_TEXTRACT,
    PDF_PROCESSING_TEXTRACT_VISION,
    PdfProcessingConfig,
    PdfProcessingResult,
    PageImage,
    WordBox,
    TextBlock,
    DetectedSegment,
    MergedRegion,
    RegionInfo,
    LineRegion,
    BlockRegion,
    TextractPageData,
    PageLoader,
    TextractLayoutExtractor,
    RegionDetector,
    LayoutAnalyzer,
    TextPreprocessor,
    RegionAnalyzer,
    RegionTranslator,
    BlockRegionTranslator,
    Renderer,
    Exporter,
    translate_pdf,
    process_pdf,
    pdf_to_images,
    run_ocr,
    build_blocks_from_tesseract,
    build_text_mask,
    build_text_mask_from_word_boxes,
    images_to_pdf,
    save_translation_mapping,
    load_translation_mapping,
    load_translation_stable_mapping,
    load_translation_canonicals,
    TEXTRACT_LOG_PATH,
    _CACHE_DIR,
    TRANSLATABLE_BLOCK_TYPES,
)
from .native import NativePage, NativeTextUnit  # noqa: F401

__all__ = [
    "PDF_TYPE_NATIVE",
    "PDF_TYPE_SCANNED",
    "PDF_PROCESSING_TEXTRACT",
    "PDF_PROCESSING_TEXTRACT_VISION",
    "PdfProcessingConfig",
    "PdfProcessingResult",
    "PageImage",
    "WordBox",
    "TextBlock",
    "DetectedSegment",
    "MergedRegion",
    "RegionInfo",
    "LineRegion",
    "BlockRegion",
    "TextractPageData",
    "PageLoader",
    "TextractLayoutExtractor",
    "RegionDetector",
    "LayoutAnalyzer",
    "TextPreprocessor",
    "RegionAnalyzer",
    "RegionTranslator",
    "BlockRegionTranslator",
    "Renderer",
    "Exporter",
    "translate_pdf",
    "process_pdf",
    "pdf_to_images",
    "run_ocr",
    "build_blocks_from_tesseract",
    "build_text_mask",
    "build_text_mask_from_word_boxes",
    "images_to_pdf",
    "save_translation_mapping",
    "load_translation_mapping",
    "load_translation_stable_mapping",
    "load_translation_canonicals",
    "TEXTRACT_LOG_PATH",
    "_CACHE_DIR",
    "TRANSLATABLE_BLOCK_TYPES",
    "NativePage",
    "NativeTextUnit",
]
